spring:
  application:
    name: civitasauto
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 30000
      max-lifetime: 1200000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: false
    open-in-view: false

# Sever Configuration
server:
  port: ${SERVER_PORT:8080}

app:
  platform-admin:
    cpf: ${CPF_PLATFORM_CPF}
    name: ${APP_PLATFORM_ADMIN_NAME}
    senha: ${APP_PLATFORM_ADMIN_PASSWORD}
  rpa:
    login: ${RPA_LOGIN}
    senha: ${RPA_SENHA}
    url-base: ${RPA_URL_BASE}
  token:
    token_secret: ${api.security.token.secret}
    token_exp: ${api.security.token.expiracao-minutos}

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    enabled: true
    operations-sorter: method
    tags-sorter: alpha